apiVersion: v1
kind: Service
metadata:
  name: javawebcalculator-service
  labels:
    app: javawebcalculator
spec:
  selector:
    app: javawebcalculator
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
